### ISSUE TITLE
About Eden Plus Mosiac

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/MyCourseware#1]
Bro, is there any way to redirect the whole game to Shift-jis? I want to translate the game
![image](https://user-images.githubusercontent.com/81801486/226084910-e0bbeae1-7ea7-43f3-b39e-c614c4928e33.png)

**Comment by Dir-A** [comment]
A few days ago, my friend asked me to help fix this problem so that the English version can display GBK encoding
In fact, I would recommend using the Japanese version to translation.

The English version changed double-byte reading of the Japanese version to single-byte reading
So there is a problem with displaying double-byte character encoding (DBCS) in English version
SJIS and GBK are very similar, both belong to DBCS

//Step1:
https://github.com/Dir-A/MyCourseware/blob/main/eden_pm_en/EdenPMHook/EdenPMHook/dllmain.cpp#L31
This is Hook CreateFont, the first parameter is charset and the second is the font name.
GBK charset -> 0x86    SJIS charset -> 0x80
HookCreateFontA(0x86, "黑体");  -> HookCreateFontA(0x80, "MS Mincho");  You can specify your own font name.

//Step2:
https://github.com/Dir-A/MyCourseware/blob/main/eden_pm_en/EdenPMHook/EdenPMHook/dllmain.cpp#L33
No change required, this just makes the game go from reading characters in single bytes to reading them in double bytes.

//Step3:
Here are the brackets for the character names like this ->  【 Lavie 】
https://github.com/Dir-A/MyCourseware/blob/main/eden_pm_en/EdenPMHook/EdenPMHook/dllmain.cpp#L59-L60
0x20,0xA1,0xBF  0xA1,0xBE,0x20   【  】  is the hexadecimal of GBK encoding of these two characters plus spaces
You can change it to SJIS encoding

https://github.com/Dir-A/MyCourseware/blob/main/eden_pm_en/EdenPMHook/EdenPMHook/dllmain.cpp#L65-L109
This is the search form for character names
It map the English character name in the script to the corresponding Japanese (SJIS) character name
This purpose is because there are some resource files in the game that are encoded in Japanese, such as animation files
When the English character name is read into the script, the character's animation needs to be played with the help of this table to find the animation files. without the correct map, the character's animation will not play.

static UCHAR aLavie[] = { 0xC0, 0xAD, 0xCE, 0xAC,0x00 }; -> the hexadecimal of GBK encoding 拉维
pTable[6] = aLavie;

0xC0, 0xAD, 0xCE, 0xAC,0x00 You can change this to SJIS encoding character name hexadecimal
Other character names are the same

//Step4:
https://github.com/Dir-A/MyCourseware/blob/main/eden_pm_en/EdenPMHook/EdenPMHook/dllmain.cpp#L111
This is the SJIS encoding boundary check, in order to display GBK need to modify here, if only display SJIS delete these codes

//Step5:
https://github.com/Dir-A/MyCourseware/blob/main/eden_pm_en/EdenPMHook/EdenPMHook/dllmain.cpp#L138C2-L181
Here is the game script pre-processing, the English script has some symbols encoded in Japanese, here the English version of the game will replace these Japanese encoded symbols with single-byte
I replaced them with GBK, if only Japanese encoding is displayed, just change all these hexadecimal to 0x90, which is the nop command in x86 asm

//Step6:
https://github.com/Dir-A/MyCourseware/blob/main/eden_pm_en/EdenPMHook/EdenPMHook/dllmain.cpp#L208
And finally this, the game converts narrow bytes to wide bytes when it finally needs to display text to screen.
That is, call WinAPI MulitiByteToWideChar to convert characters.
As this project is adapted to GBK, the CodePage parameter of MulitiByteToWideChar is 0x3A8, if it is SJIS, it will be changed to 0x3A4.

**Comment by Dir-A** [comment]
This should work, but I haven't tested it
GBK can actually display most SJIS encoded characters as well
I don't know if you want to translate into Japanese or something else

``` C
#include "Tools.h"

DWORD g_dwExeBase = (DWORD)GetModuleHandleW(NULL);

DWORD g_dwReadChar = 0x0050F227;
DWORD g_dwRetAddre = g_dwReadChar + 0x6;
VOID __declspec(naked) ProcDBCS_0()
{
	_asm
	{
		movzx esi, byte ptr[eax];
		cmp esi, 0x81;
		jb not_DBCS;

		//is_DBCS
		movzx esi, word ptr[eax];
		inc eax;

	not_DBCS:
		mov dword ptr[ebp - 0x10], esi;
		jmp g_dwRetAddre;
	}
}

VOID StartHook()
{
	HookCreateFontA(0x80, "MS Mincho");

	WriteHookCode(g_dwReadChar, (DWORD)ProcDBCS_0, 0x6);

	static BYTE aCharacterName0[] = { 0x20,0x81,0x7A };
	static BYTE aCharacterName1[] = { 0x81,0x79,0x20 };
	WriteMemory((LPVOID)(g_dwExeBase + 0x168DF4), aCharacterName0, sizeof(aCharacterName0));
	WriteMemory((LPVOID)(g_dwExeBase + 0x168DF8), aCharacterName1, sizeof(aCharacterName1));

	UCHAR** pTable = (UCHAR**)(g_dwExeBase + 0x198720);
	pTable[0] = pTable[1];
	pTable[2] = pTable[3];
	pTable[4] = pTable[5];
	pTable[6] = pTable[7];
	pTable[8] = pTable[9];
	pTable[10] = pTable[11];
	pTable[12] = pTable[13];
	pTable[14] = pTable[15];
	pTable[16] = pTable[17];

	static BYTE aProcDBCS_1_ASM[] = { 0x66, 0x89, 0x5D, 0x0C, 0x90, 0x90, 0x90 };
	WriteMemory((LPVOID)(g_dwExeBase + 0xC2971), aProcDBCS_1_ASM, sizeof(aProcDBCS_1_ASM));

	static BYTE aMapCharASM[] =
	{
		0x3D, 0x65, 0x81, 0x00, 0x00,            // cmp eax,8165          -->   ‘   SJIS
		0x75, 0x07,					             // jne eden_pm_en.4C29A9 	  	    
		0xBB, 0x65, 0x81, 0x00, 0x00,            // mov ebx,AEA1          -->   ‘   SJIS
		0xEB, 0xC8,					             // jmp eden_pm_en.4C2971 	  	    
		0x3D, 0x66, 0x81, 0x00, 0x00,            // cmp eax,8166          -->   ’   SJIS
		0x75, 0x07,					             // jne eden_pm_en.4C29B7 	  	    
		0xBB, 0x66, 0x81, 0x00, 0x00,            // mov ebx,AFA1          -->   ’   SJIS
		0xEB, 0xBA,					             // jmp eden_pm_en.4C2971 	  	 
																			 	 
		0x3D, 0x67, 0x81, 0x00, 0x00,            // cmp eax,8167           -->   “   SJIS
		0x75, 0x07,					             // jne eden_pm_en.4C29C5  	  	 
		0xBB, 0x67, 0x81, 0x00, 0x00,            // mov ebx,BAA1           -->   『   SJIS
		0xEB, 0xAC,					             // jmp eden_pm_en.4C2971  	  	 
		0x3D, 0x68, 0x81, 0x00, 0x00,            // cmp eax,8168           -->   ”   SJIS
		0x75, 0x07,					             // jne eden_pm_en.4C29D3  	  	 
		0xBB, 0x68, 0x81, 0x00, 0x00,            // mov ebx,BBA1           -->   』   SJIS
		0xEB, 0x9E,					             // jmp eden_pm_en.4C2971  	 	 
													 						 	 
		0x3D, 0x5C, 0x81, 0x00, 0x00,            // cmp eax,815C           -->   ―   SJIS
		0x75, 0x07,					             // jne eden_pm_en.4C29E1 	 	 
		0xBB, 0x5C, 0x81, 0x00, 0x00,            // mov ebx,44A8           -->   ―   SJIS
		0xEB, 0x90,					             // jmp eden_pm_en.4C2971 
												    
		0x3D, 0x96, 0x81, 0x00, 0x00,            // cmp eax,8196           -->   ＊   SJIS
		0x75, 0x07,					             // jne eden_pm_en.4C29EF 
		0xBB, 0x96, 0x81, 0x00, 0x00,            // mov ebx,AAA3           -->   ＊   SJIS
		0xEB, 0x82,					             // jmp eden_pm_en.4C2971
												    
		0x3D, 0x60, 0x81, 0x00, 0x00,            // cmp eax,8160           -->   〜   SJIS
		0x75, 0x0A,					             // jne eden_pm_en.4C2A00  
		0xBB, 0x60, 0x81, 0x00, 0x00,            // mov ebx,7E             -->   ~   ASCII
		0xE9, 0x71, 0xFF, 0xFF, 0xFF,            // jmp eden_pm_en.4C2971  
												    
		0x3D, 0xE1, 0x81, 0x00, 0x00,            // cmp eax,81E1          -->   ≪   SJIS
		0x75, 0x0A,					             // jne eden_pm_en.4C2A11
		0xBB, 0xE1, 0x81, 0x00, 0x00,            // mov ebx,3F            -->   <   ASCII
		0xE9, 0x60, 0xFF, 0xFF, 0xFF,            // jmp eden_pm_en.4C2971 
												    
		0x3D, 0xE2, 0x81, 0x00, 0x00,            // cmp eax,81E2           -->   ≫   SJIS
		0x75, 0x0A,					             // jne eden_pm_en.4C2A22  
		0xBB, 0xE2, 0x81, 0x00, 0x00,            // mov ebx,3F             -->   >   ASCII
		0xE9, 0x4F, 0xFF, 0xFF, 0xFF,            // jmp eden_pm_en.4C2971  
												    
		//Processing DBCS	   
		0x89, 0xC3,                              // mov ebx,eax          
		0xC1, 0xEB, 0x08,                        // shr ebx,8            
		0xC1, 0xE0, 0x08,                        // shl eax,8            
		0x09, 0xC3,                              // or ebx,eax    
		0x90, 0x90, 0x90, 0x90,                  // NOP
		0x90, 0x90, 0x90, 0x90
	};
	WriteMemory((LPVOID)(g_dwExeBase + 0xC299B), aMapCharASM, sizeof(aMapCharASM));

	static BYTE aProcDBCS_2_ASM[] =
	{
		0x6A, 0x02,                               // push 0x2
		0x66, 0x89, 0x45, 0xF8,                   // mov word ptr ss:[ebp-0x8], ax
		0x8D, 0x45, 0xF4,                         // lea eax, ss:[ebp-0xC]
		0x50,                                     // push eax
		0x6A, 0x02,                               // push 0x2
		0x8D, 0x4D, 0xF8,                         // lea ecx, ss:[ebp-0x8]
		0x51,                                     // push ecx
		0x6A, 0x01,                               // push 0x1
		0x68, 0xA4, 0x03, 0x00, 0x00,             // push 0x3A4
		0x89, 0x55, 0xF4,                         // mov dword ptr ss:[ebp-0xC], edx
		0xFF, 0x15, 0x10, 0x92, 0x54, 0x00,       // call dword ptr ds:[%MulitiByteToWideChar]
		0x83, 0xF8, 0x01,                         // cmp eax, 1
		0x75, 0x06,                               // jne 
		0x8B, 0x55, 0xF4,                         // mov edx, dword ptr ss:[ebp-0xC]
		0x89, 0x55, 0xFC,                         // mov dword ptr ss:[ebp-0x4], edx
		0x90, 0x90, 0x90, 0x90, 0x90, 0x90        // NOP
	};
	WriteMemory((LPVOID)(g_dwExeBase + 0x11A22F), aProcDBCS_2_ASM, sizeof(aProcDBCS_2_ASM));
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:

		StartHook();
		break;
	case DLL_THREAD_ATTACH:
	case DLL_THREAD_DETACH:
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

VOID __declspec(dllexport) DirA() {}
```

**Comment by Cosetto** [comment]
My language contains characters like á, à, é so I'm using Japanese characters to replace them.
It seems like your given code ran into some trouble
![image](https://user-images.githubusercontent.com/81801486/226108343-3aa1a4b6-c873-4e83-b129-13ef369c3ed5.png)

**Comment by Dir-A** [comment]
[EdenPMHook_mod.zip](https://github.com/Dir-A/MyCourseware/files/11008636/EdenPMHook_mod.zip)
This work with SJIS，But I don't know how you're going to display these characters with SJIS

These characters correspond to a certain DBCS encoding and should be supported by modifying the charset and codepage
![QQ截图20230318212918](https://user-images.githubusercontent.com/79064817/226109515-055c3705-946f-4ec0-a4d5-5451a861f643.png)

**Comment by Cosetto** [comment]
Thank you so much bro it works, I'm actually using modded .ttf font to replace the characters, for example: あ-á. I really want to use [SjisTunnelEncode](https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextPatch.Shared/Util/SjisTunnelEncoding.cs) of vntextpatch but the game crashes on its proxy. Also do you think the hook will work on [this game](https://vndb.org/v88) too or do I need to change the address of the code?

**Comment by Dir-A** [comment]
English steam version？I think it should be work，But something needs to be changed。

**Comment by Cosetto** [comment]
Yeah, steam version

**Comment by Dir-A** [comment]
Okay, I will check it when I have time or maybe next week

**Comment by Cosetto** [comment]
Thanks bro, can you also make a hook for Minori engine's createfileA? Some game's files are too big to repack

**Comment by imKota** [comment]
> Thanks bro, can you also make a hook for Minori engine's createfileA? Some game's files are too big to repack

@Dir-A 

for files
```c++
HANDLE WINAPI NewCreateFileA(LPCSTR lpFileName,DWORD dwDesiredAccess,DWORD dwShareMode,LPSECURITY_ATTRIBUTES lpSecurityAttributes,DWORD dwCreationDisposition,DWORD dwFlagsAndAttributes,HANDLE hTemplateFile)
{
	string strOldName(lpFileName);
	string strDirName = strOldName.substr(0, strOldName.find_last_of("\\") + 1);
	string strPazName = strOldName.substr(strOldName.find_last_of("\\") + 1);
	string strNewName;

	if (strPazName == "scr.paz")
	{
		strNewName = strDirName + "name_scr.paz";
	}
	else if (strPazName == "sys.paz")
	{
		strNewName = strDirName + "name_sys.paz";
	}
	else
	{
		strNewName = strOldName;
	}
	return CreateFileA(strNewName.c_str(),dwDesiredAccess,dwShareMode,lpSecurityAttributes,dwCreationDisposition,dwFlagsAndAttributes,hTemplateFile);
}

// (eden steam)
//PVOID pCreateFileA = (PVOID)0x005220FE;
//PVOID pCreateFileARetn = (PVOID)0x00522104;

// (eden pm steam)
PVOID pCreateFileA = (PVOID)0x0052335E;
PVOID pCreateFileARetn = (PVOID)0x00523364;
__declspec(naked) void _CreateFileA()
{ 
	__asm
	{
		call NewCreateFileA
		jmp pCreateFileARetn
	}
}

DetourAttach(&pCreateFileA, _CreateFileA);
```

for read images
```c++
//void *pSavePngName = (void*)0x004D6E3C;// (eden steam)
void *pSavePngName = (void*)0x004D74CC;// (eden pm steam)
__declspec(naked) void _SavePngName()
{
	__asm
	{
		pushad
		push eax
		call SavePngName
		popad
		jmp pSavePngName
	}
}
//void* p_old_png_read_info = (void*)0x0044A920;// (eden steam)
void* p_old_png_read_info = (void*)0x0044AB60;// (eden pm steam)
__declspec(naked) void new_png_read_info()
{
	__asm
	{
		pushad
		push[esp + 0x24]
		push eax
		call png_read_info_wrapper
		popad
		jmp p_old_png_read_info
	}
}
```

**Comment by imKota** [comment]
> Also do you think the hook will work on [this game](https://vndb.org/v88) too or do I need to change the address of the code?

You need change address for every game.

**Comment by Cosetto** [comment]
@Dir-A Bro, do you have any new on ef?

**Comment by Dir-A** [comment]
@Cosetto check this https://github.com/Dir-A/Minori_EN_MOD

**Comment by Cosetto** [comment]
Thanks so much bro, I'll check it out
